### ISSUE TITLE
XCode 11.5 dependency library compilation fails (Step 5)

### ISSUE THREAD

**Issue by zrlsid** [IBM/fhe-toolkit-macos#10]
At step 5 of the "Getting Started" guide the compilation fails on XCode 11.5 due to certification mismatch. CMake does not compile the `CMakeCCompilerId.c` or `CMakeCXXCompilerId.cpp` since no matching certification is found. It does not find the `com.ibm.research`.

```
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:
Build flags:
Id flags:

The output was:
65
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild

note: Using new build system
note: Planning build
note: Constructing build description
error: No certificate matching 'com.ibm.research' found: Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning. (in target 'CompilerIdC' from project 'CompilerIdC')
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'CompilerIdC' from project 'CompilerIdC')

** BUILD FAILED **
```

**Comment by zrlsid** [comment]
The problem was my version of `cmake`. I was running on 3.13 which apparently had an issue with the `CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED` and the `CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY` attribute handling. I changed now to version 3.17 and the dependency compiles.

**Comment by dowem** [comment]
Thank you for the report and follow up @zrlsid !  I hadn't had time to look into this, but I am pleased you found a solution. I will close this issue now since you reported that you have it working :) I hope you enjoy the toolkit and continue to contribute with bug reports or code or evangelism if you like it!

**Comment by faberga** [comment]
@zrlsid , Hi Silvio, Thank yo for reporting this issue with the "cmake" version and finding a solution. I will document this in the installation instructions for the benefit of other users who may encounter similar problem.

-Flavio

**Comment by faberga** [comment]
Reopening issue to amend install instructions.

**Comment by dowem** [comment]
@zrlsid thank you again for the report, and helping us improve our software. As you can see this issue should be fixed upstream from the merge @faberga did 4 days ago. I am going to close the issue accordingly 👍
