### ISSUE TITLE
getting error trying to build Privacy Preserving Search Applicatin

### ISSUE THREAD

**Issue by jjsenay** [IBM/fhe-toolkit-macos#11]
Having problems with a missing dependence.  Does the cmake file need to be updated?

library not found for -lhelib

[Build target Privacy Preserving Search_2020-06-08T11-06-45.txt](https://github.com/IBM/fhe-toolkit-macos/files/4747207/Build.target.Privacy.Preserving.Search_2020-06-08T11-06-45.txt)
[Build target Privacy Preserving Search_2020-06-08T11-06-45.txt](https://github.com/IBM/fhe-toolkit-macos/files/4747209/Build.target.Privacy.Preserving.Search_2020-06-08T11-06-45.txt)

**Comment by boland25** [comment]
HI, thanks for posting this issue.  In order to try and help pinpoint the problem, can you provide us with what step this was happening in the getting started?  was the script able to build the dependencies?

**Comment by jjsenay** [comment]
Thank you for the quick reply.  

I did get some Cmake error, but I just went ahead and tried to start the project.   Attached are the Cmake.logs





It happened when I did step 7 on the Github instructions.

Thanks

JJS

**Comment by boland25** [comment]
So it looks like somewhere in the dependency build, it is failing.  It is not creating the HElib_macOS directory with the HElib library in it.  It would be quite helpful if we could see the logs from the dependency script when it runs.  That will be able to tell us where it is failing.  It will print out a mess of text on the terminal after running.  If you can look through that and tell us where it is failing, or perhaps copy it into a file and attach it, that would be best.  Sorry for the trouble, hope to get it working

**Comment by jjsenay** [comment]
All,

Attached is the original, complete console output for Step 5.

JJS

**Comment by boland25** [comment]
@jjsenay i don't see anything attached, not sure it made it, unless i am missing something

**Comment by wilfred-centrality** [comment]
Same problem. Relevant stdout log:
```
[...]
++ pwd
+ CURRENT_DIR=/Users/redacted/fhe-toolkit-macos/dependencies
+ DEPEND_DIR=/Users/redacted/fhe-toolkit-macos/dependencies
+ cp /Users/redacted/fhe-toolkit-macos/dependencies/Helib_install/CMakeLists.txt /Users/redacted/fhe-toolkit-macos/dependencies/HElib
+ cd /Users/redacted/fhe-toolkit-macos/dependencies/HElib
++ pwd
+ cmake -S. -B../HElib_macOS -GXcode -DCMAKE_SYSTEM_NAME=Darwin '-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64' -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 -DCMAKE_INSTALL_PREFIX=/Users/redacted/fhe-toolkit-macos/dependencies/HElib/_install -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO -DCMAKE_IOS_INSTALL_COMBINED=YES -DGMP_DIR=/Users/redacted/fhe-toolkit-macos/dependencies/gmp -DGMP_HEADERS=/Users/redacted/fhe-toolkit-macos/dependencies/gmp/include -DGMP_LIB=/Users/redacted/fhe-toolkit-macos/dependencies/gmp/lib/libgmp.a -DNTL_INCLUDE_PATHS=/Users/redacted/fhe-toolkit-macos/dependencies/ntl/include -DNTL_LIB=/Users/redacted/fhe-toolkit-macos/dependencies/ntl/lib/ntl.a -DNTL_DIR=/Users/redacted/fhe-toolkit-macos/dependencies/ntl/include
CMake Error: The source directory "" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
+ echo ' — — — — — — — — — — Building Dependencies Script Ended — — — — — — — — — — '
 — — — — — — — — — — Building Dependencies Script Ended — — — — — — — — — —
```

*Edit:*
```
> cmake --version
cmake version 3.10.1
```

**Comment by faberga** [comment]
Hi @wilfred-centrality does you home directory have a white space or symbol on the name?
There is an known issue with white space and/o symbols in the directory name that is in the queue for fixing.

-Flavio

**Comment by faberga** [comment]
Hi @wilfred-centrality,
This seems to be a problem with the version of cmake. 
Other collaborators have reported that cmake vesrion 3.17 works. Can you let us know if it resolves your issue, please?

Thank you.

**Comment by jjsenay** [comment]
Flavio,

I get the error using Cmake 3.17.3 for MAC OS.  Downloaded binary directly from GitHub

Thanks

JJS

**Comment by dowem** [comment]
Hi @jjsenay I am just following up to see if this is still an issue. Flavio has been busy the last couple of days with the release and @boland25 has been focused on something else (though he should be back in the swing of things Monday or Tuesday of next week). Hang in there. Maybe Monday or Tuesday @boland25 or @faberga  can get some time with you to do some debugging done?

**Comment by jjsenay** [comment]
IBM,

Nobody has provided guidance on the Cmake question.  I will hang tight till next Wednesday.

Thanks

JJS

**Comment by faberga** [comment]
@jjsenay,  can you send us the complete log file,, please?

Thank you

**Comment by faberga** [comment]
@jjsenay from the terminal session where you are trying to install the toolkit, can you send us the output of the command
```bash
cmake --version
```

Thank you. Flavio

**Comment by jjsenay** [comment]
IBM,

Are there any more logs than theses?


Show-MacBook-Pro-2:~ johnsenay$ cmake --version
cmake version 3.17.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Show-MacBook-Pro-2:~ johnsenay$ 

Thanks

John J. Senay

**Comment by boland25** [comment]
@jjsenay what I am looking for is the output that is printed to the terminal after running the ./setup.sh script.  That will be able to tell me where your dependency build is failing.  I suspect that the cmake fails because something in the chain before it is failing.  It would be most helpful if I could see that

**Comment by jjsenay** [comment]
Gregory




Thanks

John J. Senay

**Comment by dowem** [comment]
@jjsenay  were you able to get the console output and attach it here as @boland25 requested? We definitely want to help you get going with this, but without some information, we are not able to provide further guidance at this time.  Can you let us know if you are still working on this?

**Comment by jjsenay** [comment]
Eli,

Yes I did.  It is the attached Cmake_build.rtf file

JJS

**Comment by dowem** [comment]
I just attached a test log. @jjsenay I don't see anything attached from you in this thread. How are you attaching them? You should be able to drag and drop the file here if it is a supported file type 

[test.rtf.log](https://github.com/IBM/fhe-toolkit-macos/files/4847165/test.rtf.log)

**Comment by boland25** [comment]
@jjsenay yes I can see @dowem's attached test log, but I do not see yours anywhere.

**Comment by jjsenay** [comment]
All,

I am trying another email account.  I am sending the attachments via :john@iiotcommunications.com <mailto:john@iiotcommunications.com>.  It is my business account on Protonmail

Sorry for the problems!!

Thanks

JJS

**Comment by dowem** [comment]
Hi Again, 

I am not sure what you mean by trying another email account. You may be viewing this discussion in an email reader, but to do the attachment, you should  be editing and posting in GitHub at this url
 
https://github.com/IBM/fhe-toolkit-macos/issues/11

If you go to the URL above, from within github, you can copy the logs by dragging and dropping them here. If you had been attaching files as email responses, I expect they are not making it to the source github issue where the team is looking for your uploads.

**Comment by jjsenay** [comment]
Here are the log files,

Thanks

JJS

[Cmake_build.txt](https://github.com/IBM/fhe-toolkit-macos/files/4848512/Cmake_build.txt)
[CMakeOutput.log](https://github.com/IBM/fhe-toolkit-macos/files/4848513/CMakeOutput.log)
[CMakeError.log](https://github.com/IBM/fhe-toolkit-macos/files/4848514/CMakeError.log)

**Comment by boland25** [comment]
ok, thanks for doing that.  I am looking at the output and it seems like the script is calling `xcrun --show-sdk-platform-path` but it can't seem to find it.  

Do you have Xcode and xcode's command line tools installed?  If you don't have Xcode you can download that from the App Store, and the command line tools can be installed by typing this into your terminal `xcode-select --install`.  If you do have Xcode and its command line tools installed perhaps there are several versions on your machine so maybe you might need to specify the path to one.  In that case you can try `xcode-select -switch /Applications/Xcode.app/Contents/Developer`.  If that didn't work, you can try to reset the path to its default by trying ` xcode-select --reset`.  please try this and re-run the `setup.sh` script to see if anything was resolved.

**Comment by jjsenay** [comment]
All,

Sorry about the delay.  The fHE compiled!!!  I will be doing more exploration next week.

Cannot thank the TEAM enough!!

JJS

[Success.pdf](https://github.com/IBM/fhe-toolkit-macos/files/4860317/Success.pdf)

**Comment by dowem** [comment]
We are happy to hear you have HElib compiled @jjsenay! Shall we leave this issue open until you can validate that you can run the privacy-preserving search application, or shall we close this issue for now?

**Comment by jjsenay** [comment]
Eki,

Please close the issue.

Thanks

John J. Senay

**Comment by jjsenay** [comment]
Eki,

Please close the issue.

Thanks

John J. Senay
