### ISSUE TITLE
Contributor instructions

### ISSUE THREAD

**Issue by faberga** [IBM/fhe-toolkit-macos#16]
Provide more detailed instructions to contributors. They should include  required tools, codiding standards,  contribution rules, etc.

**Comment by dowem** [comment]
In case anyone else is following this issue, I believe  @faberga  will provide a PR on this sometime today or tomorrow. I am writing that to ensure no one else from the community tries to pick up this issue while we wait for his forthcoming patch.

**Comment by dowem** [comment]
@faberga I think you have some text ready for this that we discussed before. I have asked Rosie to prep the content as a PR

**Comment by dowem** [comment]
As per the above history, this is merged. Closing the issue for now
