### ISSUE TITLE
Readme missing some information about the files in the repo

### ISSUE THREAD

**Issue by boland25** [IBM/fhe-toolkit-macos#18]
.workspace, .xcshareddata/xcschemes, project.pbxproj, Assets.xcassets, Base.lproj, AppDelegate... files are all missing explanations

**Comment by dowem** [comment]
I think the only 4 still without satisfactory initial explanation are as follows (as listed in Readme.md from the master branch). 

CountryData.m
CapitalDetailViewController.h
CountryTableViewController.h
CountryDisplaySplitViewController.h

**Comment by boland25** [comment]
so in obj-c there are .h files and .m files that make up a class together.  I am not sure if we need to point this out to people in the readme, and wasn't sure how to format it to make it seem that way
