### ISSUE TITLE
Installation problems, file permissions

### ISSUE THREAD

**Issue by jjsenay** [IBM/fhe-toolkit-macos#28]
All,

Had sometime to actually run the fhe toolkit after working through the Xcode problem.  Thanks fro providing the answers.

Started xcode to run the code and got a file permission error, could not write to file:

helib_macOS_SDK.xcodeproj

chmod the file, restarted xcode and the fhe-tookit got another file permission error, could not write to the file:

project.pbxproj

chmod the file restarted xcode and the application started!!  Was able to run some queries.

Some benchmarks observed:

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro9,2
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

lldb-rpc-server  % CPU 251 highest observed

Run time to completion 126 seconds was the average

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - macOS Info [ menu top left -> About this mac]:
 - cmake version [`cmake --version` in Terminal]:
 - Xcode version [Xcode -> About Xcode]:

**Terminal Output**
(please attach terminal output after running setup.sh)

**Additional context**

**Comment by boland25** [comment]
@jjsenay it sounds like you were able to resolve your problems. Thanks for the data!  If you don't have an issue can we mark this as closed? thanks!

**Comment by jjsenay** [comment]
All,

No problems, please mark this issue as closed.

Thanks for all your help

JJS

**Comment by dowem** [comment]
Thanks again for the interest and helping us improve the code and docs :) 👍
