### ISSUE TITLE
Mac OS X Privacy Preserving Search takes bad instruction error

### ISSUE THREAD

**Issue by bowlingb** [IBM/fhe-toolkit-macos#43]
**Describe the bug**
When executing the Privacy Preserving Search, when you select a country XCode indicates an error "Thread 5: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)" on line 96 in the CapitalDetailViewController.

**To Reproduce**
1. Starting from the beginning, following fhe-toolkit-macos/GettingStarted.md.  
2. Run the PrivacyPreservingSearch application.
3. Select a country
4. The focus will switch to XCode and display the error and line indicated.

**Expected behavior**
The search will complete and the capital will be displayed.
![FHE Issue](https://user-images.githubusercontent.com/169513/89112094-2ef9e500-d42c-11ea-97f6-bdb9e4b07920.jpg)
[setup_sh.txt](https://github.com/IBM/fhe-toolkit-macos/files/5011432/setup_sh.txt)
![Screen Shot 2020-08-01 at 7 23 03 PM](https://user-images.githubusercontent.com/169513/89112543-286e6c00-d432-11ea-9c09-df2650c5859f.png)
![Screen Shot 2020-08-01 at 7 22 39 PM](https://user-images.githubusercontent.com/169513/89112544-29070280-d432-11ea-8577-7c663c20fba9.png)

**Screenshots**

**Desktop (please complete the following information):**
 - macOS Info [ menu top left -> About this mac]:
 - cmake version [`cmake --version` in Terminal]:
 - Xcode version [Xcode -> About Xcode]:

**Terminal Output**
(please attach terminal output after running setup.sh)

**Additional context**

**Comment by dowem** [comment]
Thank you for the bug report, we will look into this ASAP!

**Comment by faberga** [comment]
Hi @bowlingb,, can you try a little test for us, please?
Edit line 61  of CapitalDetailViewController.mm 
`unsigned long nthreads = 63;`   and change that value to `1`.
Rebuild and rerun de app, pls?

Thanks.

**Comment by faberga** [comment]
@bowlingb What target platform/OS are you building the app for?

**Comment by bowlingb** [comment]
Hi @faberga.  I get the same result (error on line 96) setting it for just one thread.
.  
       helib::Context context(m, p, r); Thread 4: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
 
The target is Mac x64 OS X.  If you are asking something more specific, please let me know how to find the information you need.
Thanks.

**Comment by boland25** [comment]
@bowlingb can you provide us with some details about your machine that you are trying to run this on?  And just to be thorough, can you copy the output of your build dependency script and attach that here for us?  It looks like all the dependencies build properly, but just want to make sure so we don't miss something

**Comment by boland25** [comment]
@bowlingb I see the issue, you need to pull to get the latest version from master.  We updated to HElib version 1.0.2 and some of the sample code has changed.  You are on an older version

**Comment by boland25** [comment]
@bowlingb were you able to resolve your issue by updating to the latest version on master?

**Comment by bowlingb** [comment]
@boland25 It does not resolve the issue but I'm not sure that I did the pull correctly.  I'm going to start over with the "getting started" document which I would think would pick up the latest versions.

**Comment by bowlingb** [comment]
@boland25 I am back to where I started i believe.  
At this point git says:
new-user:fhe-toolkit-macos brian$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   dependencies/HElib (modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	dependencies/setup_output.txt

no changes added to commit (use "git add" and/or "git commit -a")

What do I need to do next to pull the most recent version?

**Comment by bowlingb** [comment]
[setup_output.txt](https://github.com/IBM/fhe-toolkit-macos/files/5036087/setup_output.txt)
setup_output.txt is the output from running the setup.sh script in the dependencies folder.

**Comment by boland25** [comment]
try `git fetch` and then `git pull origin master` to make sure you have the latest branch.  You should see commit # a4b9714.  If you are indeed on the latest version than something else must be going on.  will have to investigate

**Comment by boland25** [comment]
@bowlingb also I think its worth doing a fresh checkout, and going through the process from the beginning again, deleting what you have on your hard drive.  I would also get rid of the derived data that was generated.  That can be found in `<USER>/Library/Developer/Xcode/DerivedData/fhe-toolkit-macos-*` folder.

**Comment by bowlingb** [comment]
@boland25 
new-user:fhe-toolkit-macos brian$ git fetch
new-user:fhe-toolkit-macos brian$ git pull origin master
From https://github.com/IBM/fhe-toolkit-macos
 * branch            master     -> FETCH_HEAD
Already up to date.

This was done in the 'fhe-toolkit-macos' directory

**Comment by bowlingb** [comment]
@boland25 I also deleted the DerivedData subdirectories.  I now get the error "hread 3: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)" on line 1503 in file ZZ.h. 
inline long SqrRoot(long a) { return _ntl_gsqrts(a); }

**Comment by bowlingb** [comment]
Hardware Details:

Hardware Overview:

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir5,2
  Processor Name:	Dual-Core Intel Core i7
  Processor Speed:	2 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  Boot ROM Version:	264.0.0.0.0
  SMC Version (system):	2.5f9
  Serial Number (system):	C02J509NF57J
  Hardware UUID:	D0635CA3-7AB3-5BFB-B57A-BF5DDED6AC3D

Intel HD Graphics 4000:

  Chipset Model:	Intel HD Graphics 4000
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x0166
  Revision ID:	0x0009
  Metal:	Supported, feature set macOS GPUFamily1 v4
  Displays:
Color LCD:
  Display Type:	LCD
  Resolution:	1440 x 900 (Widescreen eXtended Graphics Array Plus)
  UI Looks like:	1440 x 900
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No
  Connection Type:	Internal

Memory Slots:

  ECC:	Disabled
  Upgradeable Memory:	No

BANK 0/DIMM0:

  Size:	4 GB
  Type:	DDR3
  Speed:	1600 MHz
  Status:	OK
  Manufacturer:	0x80AD
  Part Number:	0x484D5434353153364D465238412D50422020
  Serial Number:	-

BANK 1/DIMM0:

  Size:	4 GB
  Type:	DDR3
  Speed:	1600 MHz
  Status:	OK
  Manufacturer:	0x80AD
  Part Number:	0x484D5434353153364D465238412D50422020
  Serial Number:	-

**Comment by boland25** [comment]
@bowlingb I don't see anything out of the ordinary here,  it seems like its a bit of an older machine but that shouldn't matter.  I do have a similar like machine at home that I will try to test this on and see what happens.

**Comment by boland25** [comment]
@bowlingb so I was able to successfully build and test on my older MacBook from 2012.  I think that the best thing to do next to jump on a Webex call so you can walk me through what you're doing and I can see this happening for myself.  If you are up for please email me at boland@us.ibm.com and we'll setup a time to get together.
