### ISSUE TITLE
Issue while processing Accented Character

### ISSUE THREAD

**Issue by jatanloya** [IBM/fhe-toolkit-macos#48]
**Issue while processing Accented Character**
While using the Privacy Preserving Search, the capital of Iceland has accented "i" ("í") which is not displayed correctly. The problem seems to be with the Extended ASCII encoding of characters.
**To Reproduce**
1. Follow all steps according to <a href="https://github.com/IBM/fhe-toolkit-macos/blob/master/GettingStarted.md">Getting Started</a>
2. Select "Iceland" in the Privacy Preserving Search
3. Capital output is : "ReykjavF0k" , which should be "Reykjavík"

**Expected behavior**
The main issue is with how accented characters are processed by the program, ideally it should account for the accents and use the Extended ASCII value.
**Screenshots**
![Screenshot 2020-08-07 at 9 57 25 PM](https://user-images.githubusercontent.com/21239491/89667046-0c1e7380-d8f9-11ea-904e-70d11cf9b912.png)
![Screenshot 2020-08-05 at 10 28 36 PM](https://user-images.githubusercontent.com/21239491/89667154-48ea6a80-d8f9-11ea-82f2-4697ddd1bcf8.png)

**MacBook Air (13-inch, Early 2015):**
 - macOS Info : Version 10.15.6 (19G73)
 - cmake version : 3.17.1
 - Xcode version : Version 11.6 (11E708)

**Comment by dowem** [comment]
Good find @jatanloya! Thank you for reporting this to us. We will try to get this fixed early next week!

**Comment by boland25** [comment]
should be closed once PR #55 is accepted

**Comment by faberga** [comment]
@jatanloya The current implementation does not support extended ASCII characters.

**Comment by jatanloya** [comment]
@faberga Alright, I'll close the issue.
