### ISSUE TITLE
Typo in the setup.sh script @ line 202

### ISSUE THREAD

**Issue by zrlsid** [IBM/fhe-toolkit-macos#65]
**Describe the bug**
The `setup.sh` script does not build the `HELib` as there is a typo in the parameter list of the `cmake`
 command.

Current line @ 202:
`-DNTL_LIB="${DEPEND_DIR}/ntl/lib/ntl.a" \`

The correct library path is actually:
`-DNTL_LIB="${DEPEND_DIR}/ntl/libs/ntl.a" \`

note the **s** in the directory name **libs**

With this fix, it did build the `HELib` with the script.

**Comment by dowem** [comment]
@boland25 I just committed the fix to this to master. I wanted to point it out to you  in case it had somehow slipped through testing. Thank you @zrlsid! Much appreciated Silvio!
