### ISSUE TITLE
SecTaskLoadEntitlements` failed error=22 cs_flags=20, pid=33722

### ISSUE THREAD

**Issue by 0zoe** [IBM/fhe-toolkit-macos#77]
**Describe the bug**
>  error：SecTaskLoadEntitlements` failed error=22 cs_flags=20, pid=33722

**Screenshots**

> ![截屏2021-10-29 下午3 45 39](https://user-images.githubusercontent.com/92904277/139397780-d9255ce2-2ea9-491c-b694-088584559e54.png)

> ![截屏2021-10-29` 下午3 45 58](https://user-images.githubusercontent.com/92904277/139397820-6e3341a3-d805-4755-b624-64f197dcf288.png)

**Desktop (please complete the following information):**
 - macOS Info [ menu top left -> About this mac]:  11.6.1 (20G221)
 - cmake version [`cmake --version` in Terminal]: 3.20.3
 - Xcode version [Xcode -> About Xcode]:  13.0 (13A233)

**Terminal Output**
> [setup.log](https://github.com/IBM/fhe-toolkit-macos/files/7439988/setup.log)

**Comment by boland25** [comment]
thanks for pointing this out, I will have a look

**Comment by boland25** [comment]
This is an entitlement issue for writing to a directory on the disk.  can fix but will be a bit

**Comment by 0zoe** [comment]
Hi,
你好！


1）非常感谢您及时回复！


2）请您给出优质的解决方案；直至在此环境下，项目可以正常运行


3）请给出具体的解决方案。



在此感谢您的帮助！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IBM/fhe-toolkit-macos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 凌晨2:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IBM/fhe-toolkit-macos] SecTaskLoadEntitlements` failed error=22 cs_flags=20, pid=33722 (Issue #77)





 
This is an entitlement issue for writing to a directory on the disk.  can fix but will be a bit
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by boland25** [comment]
@0zoe  you can try this branch https://github.com/IBM/fhe-toolkit-macos/tree/env_var_settings.  Its not ready for a PR, but I have tested it and it is running in Xcode 13 & 12

**Comment by boland25** [comment]
has been merged, please let me know if its still an issue, but we believe the problem has been resolved
